#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate components/mono_gfx/src/fonts.cpp from TrueType fonts.

The fonts are DejaVu Sans (Bitstream Vera licence, compatible with the GPL).
On Debian and Ubuntu they are in the fonts-dejavu-core package.

Usage: python3 tools/fonts/generate_fonts.py
Needs: Pillow (python3-pil)
"""

from dataclasses import dataclass
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

REPO_DIR = Path(__file__).resolve().parents[2]
OUTPUT_PATH = REPO_DIR / "components" / "mono_gfx" / "src" / "fonts.cpp"
FONT_DIR = Path("/usr/share/fonts/truetype/dejavu")
FIRST_CHAR = 32
LAST_CHAR = 126
THRESHOLD = 128


@dataclass(frozen=True)
class FontSpec:
    name: str
    file_name: str
    size_px: int


FONT_SPECS = [
    FontSpec("kFontSmall", "DejaVuSans.ttf", 12),
    FontSpec("kFontMedium", "DejaVuSans-Bold.ttf", 17),
    FontSpec("kFontLarge", "DejaVuSans-Bold.ttf", 40),
]


def render_font(spec: FontSpec) -> tuple[list[int], list[tuple[int, int, int]], int, int]:
    font = ImageFont.truetype(str(FONT_DIR / spec.file_name), spec.size_px)
    ascent, descent = font.getmetrics()
    height = ascent + descent
    bitmap: list[int] = []
    glyphs: list[tuple[int, int, int]] = []

    for code in range(FIRST_CHAR, LAST_CHAR + 1):
        character = chr(code)
        advance = round(font.getlength(character))
        left, _, right, _ = font.getbbox(character)
        width = max(advance, right, 1)
        image = Image.new("L", (width, height), 0)
        ImageDraw.Draw(image).text((0, 0), character, font=font, fill=255)
        offset = len(bitmap)
        bytes_per_row = (width + 7) // 8
        for row in range(height):
            row_bytes = [0] * bytes_per_row
            for column in range(width):
                if image.getpixel((column, row)) >= THRESHOLD:
                    row_bytes[column // 8] |= 0x80 >> (column % 8)
            bitmap.extend(row_bytes)
        glyphs.append((offset, width, advance))

    return bitmap, glyphs, height, ascent


def format_bytes(values: list[int]) -> str:
    lines = []
    for start in range(0, len(values), 16):
        chunk = values[start : start + 16]
        lines.append("    " + ", ".join(f"0x{value:02X}" for value in chunk) + ",")
    return "\n".join(lines)


def main() -> None:
    parts = [
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "// Generated by tools/fonts/generate_fonts.py from DejaVu Sans. Do not edit.",
        '#include "mono_gfx/font.hpp"',
        "",
        "namespace mono_gfx {",
        "",
        "namespace {",
        "",
    ]
    definitions = []

    for spec in FONT_SPECS:
        bitmap, glyphs, height, baseline = render_font(spec)
        stem = spec.name[1:].lower()
        parts.append(f"// {spec.file_name}, {spec.size_px} px")
        parts.append(f"constexpr std::uint8_t {stem}_bitmap[] = {{")
        parts.append(format_bytes(bitmap))
        parts.append("};")
        parts.append("")
        parts.append(f"constexpr Glyph {stem}_glyphs[] = {{")
        for code, (offset, width, advance) in zip(range(FIRST_CHAR, LAST_CHAR + 1), glyphs):
            label = "space" if code == 32 else ("backslash" if code == 92 else chr(code))
            parts.append(f"    {{{offset}, {width}, {advance}}},  // {label}")
        parts.append("};")
        parts.append("")
        definitions.append(
            f"const Font {spec.name} = {{{stem}_bitmap, {stem}_glyphs, '{chr(FIRST_CHAR)}', "
            f"'{chr(LAST_CHAR)}', {height}, {baseline}}};"
        )

    parts.append("}  // namespace")
    parts.append("")
    parts.extend(definitions)
    parts.append("")
    parts.append("}  // namespace mono_gfx")
    parts.append("")
    OUTPUT_PATH.write_text("\n".join(parts))
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_DIR)}")


if __name__ == "__main__":
    main()
